#!/bin/sh

os=$(uname -s)
bindir=''
mandir=''
if [ $os = 'Linux' ]; then
    bindir='/usr/bin/'
    mandir='/usr/share/man/man1/'
elif [ $os = 'Darwin' ]; then
    bindir='/usr/local/bin/'
    mandir='/usr/local/share/man/man1/'
else
    echo unsupported operating system
fi

install_bin() {
    if test -d $bindir; then
        if test -f $bindir'pruner'; then
            while true; do
                read -p "Existing pruner command found: overwrite? " ans
                case $ans in
                    [Yy]* ) echo Overwriting pruner command.; break;;
                    [Nn]* ) echo 'Cancelling install'; exit;;
                    * ) echo "Please answer yes [Y/y] or no [N/n].";;
                esac
            done
        fi
        chmod +x "src/pruner"
        sudo cp "src/pruner" $bindir
    else
        echo Issue locating appropriate directory: $bindir\nFailed to Install.
        exit 1
    fi
}

install_man() {
    if test -d $mandir; then
        sudo cp 'doc/pruner.1' $mandir
        echo Command successfully installed.
    else
        echo Issue locating appropriate directory: $mandir\nFailed to Install.
        exit 1
    fi
}

install_bin
install_man
