.TH clean 1 "10 October 2017" "1.0" "clean man page"

.SH NAME
clean -- lightweight project pruner

.SH SYNOPSIS
clean [SUBDIRECTORY] [-saw] [-f FILE] [-d DIRECTORY]

.SH DESCRIPTION
A configurable file/folder removal command in which you can specify which 
files and directories you choose to delete by simply running the command.
You can choose which directory (DIR) to clean from; the files (-f)/
folders (-d) you specified (via initial clean or -a). If you find 
that you no longer need to remove those files, you can write (-w) 
over your current configuration. If you don't appreciate the 
output, you can also silent (-s) it.

.SH OPTIONS
.TP
.B -d
path of directory/directories to be removed

.TP
.B -f
path of file/files to be removed

.TP
.B -a
add another file/directory to be removed

.TP
.B -w
write over your current settings

.TP
.B -s
silent output

.SH AUTHOR
Brandon Johnson | brandon.johnson.official@gmail.com
