.TH pruner 1 "10 October 2017" "1.0" "pruner man page"

.SH NAME
pruner -- lightweight project pruner

.SH SYNOPSIS
pruner [-iwv] [-r param] [-f file] [-d directory]

.SH DESCRIPTION
A configurable file/folder removal command in which you can specify which 
files and directories you choose to delete by simply running the command.
You can choose which directory (DIR) to pruner from; the files (-f)/
folders (-d) you specified (via initial pruner or -a). If you find 
that you no longer need to remove those files, you can wipe (-w) 
your current configuration. If you don't appreciate the silence, 
you can always set verbose (-v) output. If you realize you no 
longer need to prune certain files/folders, feel free to 
remove (-r) said parameter from the .prune tracker.

.SH OPTIONS
.TP
.B -d
path of directory/directories to be removed

.TP
.B -f
path of file/files to be removed

.TP
.B -r
remove files/folders to be pruned

.TP
.B -i
list files/folders to be pruned

.TP
.B -v
verbose console output

.TP
.B -w
wipe .prune file

.SH AUTHOR
Brandon Johnson | brandon.johnson.official@gmail.com
